### ISSUE TITLE
Any plans to support HLSL?

### ISSUE THREAD

**Issue by ongamex** [ARM-software/spir2cross#2]
Are there any plans to support HLSL? If yes, which is the minimal FEATURE LEVEL?

**Comment by HansKristian-ARM** [comment]
It's likely to happen at some point, but there's no concrete timescale. Feature level would probably depend on what the SPIR-V is using.

**Comment by HansKristian-ARM** [comment]
This project has been adopted by Khronos, and is now hosted here: https://github.com/KhronosGroup/SPIRV-Cross. This repository will be disabled shortly.
