### ISSUE TITLE
Retrieving member count

### ISSUE THREAD

**Issue by chaoticbob** [ARM-software/spir2cross#5]
Hi, is there a way to retrieve the number of members that belongs to a block? I added in a method to do this directly - but was wondering if there was already and existing way to do this? Thanks

**Comment by Themaister** [comment]
I think you could do something like

```
size_t num_members = compiler.get_type(resource.type_id).member_types.size();
```

**Comment by HansKristian-ARM** [comment]
I think you could do something like

```
size_t num_members = compiler.get_type(resource.type_id).member_types.size();
```

**Comment by chaoticbob** [comment]
Thanks.
