### ISSUE TITLE
"Over 3 compilation loops detected" when using atomic op on image

### ISSUE THREAD

**Issue by ChrisGautier** [ARM-software/spir2cross#7]
When decompiling a SPIR-V shader that contains this:

          %9 = OpTypeInt 32 0
          ...
         %28 = OpTypeImage %9 1D 0 1 0 2 R32ui
         %29 = OpTypePointer UniformConstant %28
         %30 = OpVariable %29 UniformConstant
          ...
         %36 = OpVariable %29 UniformConstant
         %54 = OpTypePointer Image %9
          ...
         %31 = OpLoad %28 %30
          ...
         %55 = OpImageTexelPointer %54 %36 %41 %13
         %56 = OpAtomicIAdd %9 %55 %19 %13 %53
         %58 = OpCompositeConstruct %57 %56 %56 %56 %56
               OpImageWrite %31 %35 %58

SPIR2CROSS crashes with this message (with some printf enabled)

    Expression 31 was invalidated due to variable 30 being invalid at read time!
    Expression 31 was invalidated due to variable 30 being invalid at read time!
    Expression 31 was invalidated due to variable 30 being invalid at read time!
    terminate called after throwing an instance of 'spir2cross::CompilerError'
    what():  Over 3 compilation loops detected. Must be a bug!

I think accessing an image through **OpAtomicIAdd** should not invalidate the image variable itself. I can work around the crash with this change:

    diff --git spir2glsl.cpp spir2glsl.cpp
    index 926d062..2816fac 100644
    --- spir2glsl.cpp
    +++ spir2glsl.cpp
    @@ -2933,7 +2933,7 @@ void CompilerGLSL::emit_instruction(const Instruction &i)
                 const char *op = check_atomic_image(ops[2]) ? "imageAtomicAdd" : "atomicAdd";
                 forced_temporaries.insert(ops[1]);
                 emit_binary_func_op(ops[0], ops[1], ops[2], ops[5], op);
    -            flush_all_atomic_capable_variables();
    +            //flush_all_atomic_capable_variables();
                 register_read(ops[1], ops[2], should_forward(ops[2]));
                 break;
             }

**Comment by HansKristian-ARM** [comment]
Reproduced and fixed, the problem was indeed that opaque variables took a dependency on the pointer-to-image, which was not intended. Also fixes some other cleanliness issues in reference output at the same time.

**Comment by ChrisGautier** [comment]
I confirm the issue is now corrected. Thanks for the quick fix :+1:
